### ISSUE TITLE
Proposal to use profiles instead access_key/access_secret

### ISSUE THREAD

**Issue by bogdangi** [zutherb/terraform-dcos#3]
Hi, I want to add proposal to yse profiles enstead using access_key/access_secret.
I think it makes sence if you have different cluster running on different environment.
What do you think?

**Comment by zot24** [comment]
Or just don't force a `provider` inside this module and let the people set their own when calling it.

**Comment by zutherb** [comment]
Hi @bogdangi, in our production and dev setup we override the aws_access_key variable with the TF_VARS see https://www.terraform.io/docs/configuration/variables.html
