### ISSUE TITLE
How to use vpn?

### ISSUE THREAD

**Issue by bogdangi** [zutherb/terraform-dcos#4]
Hi I have one question after I have the cluster up and runnig I cannot understand how to use VPN with it.
I would be nice to have a link to how to use some where in documentation.

**Comment by macedigital** [comment]
Just to clarify, it's not possible to login on the OpenVPN Admin UI page with admin/admin-pw. The password is correct, but the page states 'LOCKOUT', see screenshot

![screenshot from 2017-04-05 12-30-52](https://cloud.githubusercontent.com/assets/248495/24701702/c6c32bb0-19fb-11e7-9b71-85b79cb877a0.png)

**Comment by macedigital** [comment]
@zutherb Can you have a look, applying #5 fixed the issue for us.
