### ISSUE TITLE
Critical Security issue

### ISSUE THREAD

**Issue by lordnynex** [zutherb/terraform-dcos#6]
Hello,

I have discovered a critical security issue with this module. Please let me know if you'd like me to disclose the issue publicly here in this issue, or if you'd like me to email about what the issue is.

**Comment by lordnynex** [comment]
Please see dcos/dcos#1484 for information about the issue and the fix. This unfortunately requires an upgrade, but it is trivial to change the configuration on a running system. Users should be encouraged to upgrade or manually resolve the issue in any public facing clusters.

**Comment by jgehrcke** [comment]
Note that we could still sanitize https://github.com/zutherb/terraform-dcos/blob/c30ebe7885f2b3904d3567cabb7b8a540cb5c856/slave_user_data.yml#L157. However, one of the most important observations here is that the entire approach used here uses a private interface and is therefore highly error-prone.
